import {
  Wallet,
  PiggyBank,
  CreditCard,
  DollarSign,
  TrendingUp,
  ShoppingCart,
  Coffee,
  Utensils,
  Home,
  Car,
  Heart,
  Gift,
  Plane,
  Book,
  Briefcase,
  Gamepad2,
  Music,
  Smartphone,
  Laptop,
  Cpu,
  Bot,
  Cloud,
  Camera,
  Sun,
  Moon,
  CloudRain,
  Flame,
  Droplets,
  Snowflake,
  Leaf,
  TreePine,
  Mountain,
  Dog,
  Cat,
  PawPrint,
  PersonStanding,
  Users,
  Baby,
  Shirt,
  BedDouble,
  Dumbbell,
  Bike,
  Trophy,
  Globe,
  Rocket,
  Castle,
  Wand2,
  Star,
  Brush,
  Palette,
  Hammer,
  Shield,
} from "lucide-react";

export const categories = [
  { id: "101", name: "Dining out", type: "expense", icon: "Utensils", color: "bg-rose-500", category_group: "Family" },
  { id: "102", name: "Shopping", type: "expense", icon: "ShoppingBag", color: "bg-purple-500", category_group: "Personal" },
  { id: "103", name: "Transportation", type: "expense", icon: "Car", color: "bg-yellow-500", category_group: "Travel" },
  { id: "104", name: "Utilities", type: "expense", icon: "Home", color: "bg-blue-500", category_group: "Household" },
  { id: "105", name: "Entertainment", type: "expense", icon: "Zap", color: "bg-pink-500", category_group: "Leisure" },
  // { id: "106", name: "Groceries", type: "expense", icon: "ShoppingCart", color: "bg-green-500", category_group: "Family" },
  // { id: "107", name: "Healthcare", type: "expense", icon: "Heart", color: "bg-red-500", category_group: "Personal" },
  // { id: "108", name: "Education", type: "expense", icon: "BookOpen", color: "bg-indigo-500", category_group: "Personal Development" },
  // { id: "109", name: "Savings", type: "income", icon: "PiggyBank", color: "bg-teal-500", category_group: "Financial" },
  // { id: "110", name: "Salary", type: "income", icon: "DollarSign", color: "bg-green-600", category_group: "Financial" },
];

export const MONTHLY_BUDGET = 25000;

export const categoryIcons = [
  { name: "Wallet", icon: Wallet },
  { name: "PiggyBank", icon: PiggyBank },
  { name: "CreditCard", icon: CreditCard },
  { name: "DollarSign", icon: DollarSign },
  { name: "TrendingUp", icon: TrendingUp },
  { name: "ShoppingCart", icon: ShoppingCart },
  { name: "Coffee", icon: Coffee },
  { name: "Utensils", icon: Utensils },
  { name: "Home", icon: Home },
  { name: "Car", icon: Car },
  { name: "Heart", icon: Heart },
  { name: "Gift", icon: Gift },
  { name: "Plane", icon: Plane },
  { name: "Book", icon: Book },
  { name: "Briefcase", icon: Briefcase },
  { name: "Gamepad2", icon: Gamepad2 },
  { name: "Music", icon: Music },
  { name: "Smartphone", icon: Smartphone },
  { name: "Laptop", icon: Laptop },
  { name: "Cpu", icon: Cpu },
  { name: "Bot", icon: Bot },
  { name: "Cloud", icon: Cloud },
  { name: "Camera", icon: Camera },
  { name: "Sun", icon: Sun },
  { name: "Moon", icon: Moon },
  { name: "CloudRain", icon: CloudRain },
  { name: "Flame", icon: Flame },
  { name: "Droplets", icon: Droplets },
  { name: "Snowflake", icon: Snowflake },
  { name: "Leaf", icon: Leaf },
  { name: "TreePine", icon: TreePine },
  { name: "Mountain", icon: Mountain },
  { name: "Dog", icon: Dog },
  { name: "Cat", icon: Cat },
  { name: "PawPrint", icon: PawPrint },
  { name: "PersonStanding", icon: PersonStanding },
  { name: "Users", icon: Users },
  { name: "Baby", icon: Baby },
  { name: "Shirt", icon: Shirt },
  { name: "BedDouble", icon: BedDouble },
  { name: "Dumbbell", icon: Dumbbell },
  { name: "Bike", icon: Bike },
  { name: "Trophy", icon: Trophy },
  { name: "Globe", icon: Globe },
  { name: "Rocket", icon: Rocket },
  { name: "Castle", icon: Castle },
  { name: "Wand2", icon: Wand2 },
  { name: "Star", icon: Star },
  { name: "Brush", icon: Brush },
  { name: "Palette", icon: Palette },
  { name: "Hammer", icon: Hammer },
  { name: "Shield", icon: Shield },
];