import * as LucideIcons from "lucide-react";

export const categories = [
  { id: "101", category_name: "Dining out", type: "expense", icon: "Utensils", color: "bg-rose-500", category_group: "Family" },
  { id: "102", category_name: "Shopping", type: "expense", icon: "ShoppingBag", color: "bg-purple-500", category_group: "Personal" },
  { id: "103", category_name: "Transportation", type: "expense", icon: "Car", color: "bg-yellow-500", category_group: "Travel" },
  { id: "104", category_name: "Utilities", type: "expense", icon: "Home", color: "bg-blue-500", category_group: "Household" },
  { id: "105", category_name: "Entertainment", type: "expense", icon: "Zap", color: "bg-pink-500", category_group: "Leisure" },
  // { id: "106", name: "Groceries", type: "expense", icon: "ShoppingCart", color: "bg-green-500", category_group: "Family" },
  // { id: "107", name: "Healthcare", type: "expense", icon: "Heart", color: "bg-red-500", category_group: "Personal" },
  // { id: "108", name: "Education", type: "expense", icon: "BookOpen", color: "bg-indigo-500", category_group: "Personal Development" },
  // { id: "109", name: "Savings", type: "income", icon: "PiggyBank", color: "bg-teal-500", category_group: "Financial" },
  // { id: "110", name: "Salary", type: "income", icon: "DollarSign", color: "bg-green-600", category_group: "Financial" },
];

export const MONTHLY_BUDGET = 25000;

export const categoryIcons = [
  { name: "Wallet", icon: LucideIcons.Wallet },
  { name: "PiggyBank", icon: LucideIcons.PiggyBank },
  { name: "CreditCard", icon: LucideIcons.CreditCard },
  { name: "DollarSign", icon: LucideIcons.DollarSign },
  { name: "TrendingUp", icon: LucideIcons.TrendingUp },
  { name: "ShoppingCart", icon: LucideIcons.ShoppingCart },
  { name: "Coffee", icon: LucideIcons.Coffee },
  { name: "Utensils", icon: LucideIcons.Utensils },
  { name: "Home", icon: LucideIcons.Home },
  { name: "Car", icon: LucideIcons.Car },
  { name: "Heart", icon: LucideIcons.Heart },
  { name: "Gift", icon: LucideIcons.Gift },
  { name: "Plane", icon: LucideIcons.Plane },
  { name: "Book", icon: LucideIcons.Book },
  { name: "Briefcase", icon: LucideIcons.Briefcase },
  { name: "Gamepad2", icon: LucideIcons.Gamepad2 },
  { name: "Music", icon: LucideIcons.Music },
  { name: "Smartphone", icon: LucideIcons.Smartphone },
  { name: "Laptop", icon: LucideIcons.Laptop },
  { name: "Cpu", icon: LucideIcons.Cpu },
  { name: "Bot", icon: LucideIcons.Bot },
  { name: "Cloud", icon: LucideIcons.Cloud },
  { name: "Camera", icon: LucideIcons.Camera },
  { name: "Sun", icon: LucideIcons.Sun },
  { name: "Moon", icon: LucideIcons.Moon },
  { name: "CloudRain", icon: LucideIcons.CloudRain },
  { name: "Flame", icon: LucideIcons.Flame },
  { name: "Droplets", icon: LucideIcons.Droplets },
  { name: "Snowflake", icon: LucideIcons.Snowflake },
  { name: "Leaf", icon: LucideIcons.Leaf },
  { name: "TreePine", icon: LucideIcons.TreePine },
  { name: "Mountain", icon: LucideIcons.Mountain },
  { name: "Dog", icon: LucideIcons.Dog },
  { name: "Cat", icon: LucideIcons.Cat },
  { name: "PawPrint", icon: LucideIcons.PawPrint },
  { name: "PersonStanding", icon: LucideIcons.PersonStanding },
  { name: "Users", icon: LucideIcons.Users },
  { name: "Baby", icon: LucideIcons.Baby },
  { name: "Shirt", icon: LucideIcons.Shirt },
  { name: "BedDouble", icon: LucideIcons.BedDouble },
  { name: "Dumbbell", icon: LucideIcons.Dumbbell },
  { name: "Bike", icon: LucideIcons.Bike },
  { name: "Trophy", icon: LucideIcons.Trophy },
  { name: "Globe", icon: LucideIcons.Globe },
  { name: "Rocket", icon: LucideIcons.Rocket },
  { name: "Castle", icon: LucideIcons.Castle },
  { name: "Wand2", icon: LucideIcons.Wand2 },
  { name: "Star", icon: LucideIcons.Star },
  { name: "Brush", icon: LucideIcons.Brush },
  { name: "Palette", icon: LucideIcons.Palette },
  { name: "Hammer", icon: LucideIcons.Hammer },
  { name: "Shield", icon: LucideIcons.Shield },
];